# Generated by Django 2.0.3 on 2020-05-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200515_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='pizza',
            new_name='pizzas',
        ),
    ]
