# Generated by Django 3.0.6 on 2020-05-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
