# Generated by Django 2.2 on 2020-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_food', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('option', models.CharField(max_length=120)),
                ('big_size', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
